// Domain mapping for better logo hit rates
const DOMAIN_MAP: Record<string, string> = {
  AAPL: "apple.com",
  MSFT: "microsoft.com",
  GOOGL: "abc.xyz",
  GOOG: "google.com",
  AMZN: "amazon.com",
  TSLA: "tesla.com",
  META: "meta.com",
  NVDA: "nvidia.com",
  NFLX: "netflix.com",
  ADBE: "adobe.com",
  CRM: "salesforce.com",
  ORCL: "oracle.com",
  CSCO: "cisco.com",
  INTC: "intel.com",
  AMD: "amd.com",
  QCOM: "qualcomm.com",
  AVGO: "broadcom.com",
  TXN: "ti.com",
  MU: "micron.com",
  AMAT: "appliedmaterials.com",
  LRCX: "lamresearch.com",
  KLAC: "kla.com",
  ASML: "asml.com",
  TSM: "tsmc.com",
  SMCI: "supermicro.com",
  PLTR: "palantir.com",
  SNOW: "snowflake.com",
  MDB: "mongodb.com",
  DDOG: "datadoghq.com",
  CRWD: "crowdstrike.com",
  ZS: "zscaler.com",
  OKTA: "okta.com",
  TEAM: "atlassian.com",
  WDAY: "workday.com",
  NOW: "servicenow.com",
  SPLK: "splunk.com",
  PATH: "uipath.com",
  RBLX: "roblox.com",
  UBER: "uber.com",
  LYFT: "lyft.com",
  DASH: "doordash.com",
  SHOP: "shopify.com",
  SQ: "squareup.com",
  PYPL: "paypal.com",
  COIN: "coinbase.com",
  ROKU: "roku.com",
  SPOT: "spotify.com",
  ZM: "zoom.us",
  DOCU: "docusign.com",
  TWLO: "twilio.com",
  SNAP: "snap.com",
  PINS: "pinterest.com",
  YELP: "yelp.com",
  ETSY: "etsy.com",
  BKNG: "booking.com",
  EXPE: "expedia.com",
  ABNB: "airbnb.com",
  MAR: "marriott.com",
  HLT: "hilton.com",
  DIS: "disney.com",
  CMCSA: "comcast.com",
  CHTR: "charter.com",
  VZ: "verizon.com",
  T: "att.com",
  TMUS: "t-mobile.com",
  V: "visa.com",
  MA: "mastercard.com",
  AXP: "americanexpress.com",
  JPM: "jpmorganchase.com",
  BAC: "bankofamerica.com",
  WFC: "wellsfargo.com",
  GS: "goldmansachs.com",
  MS: "morganstanley.com",
  SCHW: "schwab.com",
  BLK: "blackrock.com",
  SPGI: "spglobal.com",
  MCO: "moodys.com",
  ICE: "theice.com",
  CME: "cmegroup.com",
  NDAQ: "nasdaq.com",
  CBOE: "cboe.com",
  COF: "capitalone.com",
  USB: "usbank.com",
  PNC: "pnc.com",
  TFC: "truist.com",
  KEY: "key.com",
  HBAN: "huntington.com",
  FITB: "53.com",
  RF: "regions.com",
  ZION: "zionbank.com",
  CMA: "comerica.com",
  MTB: "mtb.com",
  STT: "statestreet.com",
  NTRS: "northerntrust.com",
  BNY: "bnymellon.com",
  TROW: "troweprice.com",
  IVZ: "invesco.com",
  AMP: "ameriprise.com",
  BEN: "franklinresources.com",
  LM: "leggmason.com",
  APAM: "artisanpartners.com",
  EV: "eatonvance.com",
  WDR: "waddellreed.com",
  JHG: "janushenderson.com",
  AB: "alliancebernstein.com",
  KKR: "kkr.com",
  BX: "blackstone.com",
  APO: "apollo.com",
  CG: "carlyle.com",
  OAK: "oaktree.com",
  AINV: "apollo.com",
  ARCC: "ares.com",
  BDC: "belden.com",
  FSK: "fsinvestments.com",
  MAIN: "mainstcapital.com",
  NEWT: "newtekone.com",
  PSEC: "prospectcapital.com",
  SAR: "saracen.com",
  TCPC: "tcpcapital.com",
  TSLX: "sixthstreet.com",
  WHF: "whitehorsefinance.com",
  XFLT: "xainvestments.com"
}

export const logoUrlFor = (symbol: string, domain?: string) => {
  if (domain) {
    return `https://logo.clearbit.com/${domain}`
  }
  
  const mappedDomain = DOMAIN_MAP[symbol.toUpperCase()]
  if (mappedDomain) {
    return `https://logo.clearbit.com/${mappedDomain}`
  }
  
  return `https://logo.clearbit.com/${symbol.toLowerCase()}.com`
}
